version: '2'

services:
  ruby-sgx:
    image: enclaive/ruby-sgx
    container_name: "ruby-sgx"
    build: .
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
